service: nlt-aoi-tool

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  architecture: arm64
  memorySize: 1024
  timeout: 10
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_OPTIONS: --enable-source-maps

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node20
    platform: node
    concurrency: 10
    exclude: []

functions:
  api:
    handler: src/handler.http
    events:
      - httpApi:
          path: /aoi
          method: post
